trigger: none

parameters:
  - name: testFile
    type: string
    default: 'loginTest.cy.js'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CypressTests
  displayName: 'Run Cypress Tests and Upload Videos'
  steps:
    - checkout: self

    - script: |
        echo "Running test: ${{ parameters.testFile }}"
        docker run --rm \
          -v $PWD:/e2e \
          -w /e2e \
          cypress/included:13.6.4 \
          run --spec "cypress/e2e/${{ parameters.testFile }}"
      displayName: 'Run Cypress Test'

    - script: |
        if [ -d "$(System.DefaultWorkingDirectory)/cypress/videos" ]; then
          echo "##vso[task.setvariable variable=hasVideos]true"
        else
          echo "##vso[task.setvariable variable=hasVideos]false"
        fi
      displayName: 'Check if Cypress videos exist'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Cypress test videos'
      condition: and(succeededOrFailed(), eq(variables.hasVideos, 'true'))
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/cypress/videos'
        artifactName: 'cypress-videos'
