trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CypressTests
  displayName: 'Run Cypress Tests and Upload Videos'
  steps:
    # Checkout your repo
    - checkout: self

    # Optional: Build custom Docker image with Cypress + VNC (skip if not needed)
    - script: |
        docker build -t cypress-vnc .
      displayName: 'Build custom Cypress + VNC Docker image'
      continueOnError: true  # Optional: allow pipeline to continue even if this fails

    # Run Cypress tests inside Docker
    - script: |
        docker run --rm \
          -v $PWD:/e2e \
          -w /e2e \
          cypress/included:13.6.4 \
          run
      displayName: 'Run Cypress Tests'

    # Optional: Print Cypress videos folder if it exists
    - script: |
        if [ -d "$(System.DefaultWorkingDirectory)/cypress/videos" ]; then
          echo "Videos found:"
          ls -R $(System.DefaultWorkingDirectory)/cypress/videos
        else
          echo "No Cypress videos directory found."
        fi
      displayName: 'Check for Cypress videos'

    # Upload videos only if they exist
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Cypress test videos'
      condition: and(succeededOrFailed(), exists('$(System.DefaultWorkingDirectory)/cypress/videos'))
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/cypress/videos'
        artifactName: 'cypress-videos'
