trigger:
- main

parameters:
  - name: testFiles
    type: string
    default: ''

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CypressTests
  displayName: 'Run Cypress Tests'
  steps:
    - checkout: self

    - task: CmdLine@2
      displayName: 'Run Cypress Tests'
      inputs:
        script: |
          if [ -z "${{ parameters.testFiles }}" ]; then
            echo "No testFiles parameter provided — running all tests"
            docker run --rm \
              -v $PWD:/e2e \
              -w /e2e \
              cypress/included:13.6.4 \
              run
          else
            echo "Running tests matching: ${{ parameters.testFiles }}"
            docker run --rm \
              -v $PWD:/e2e \
              -w /e2e \
              cypress/included:13.6.4 \
              run --spec "${{ parameters.testFiles }}"
          fi
