trigger:
  branches:
    include:
      - main

parameters:
  - name: testFolder
    type: string
    default: ''

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: __default
  jobs:
  - job: CypressTests
    displayName: 'Run Cypress Tests'
    steps:
    - checkout: self

    - script: |
        echo "🧪 testFolder param = '${{ parameters.testFolder }}'"

        if [ -z "${{ parameters.testFolder }}" ]; then
          echo "📂 No folder specified. Running ALL tests..."
          docker run --rm \
            -v $PWD:/e2e \
            -w /e2e \
            cypress/included:13.6.4 \
            run
        else
          echo "📂 Running tests in folder: cypress/e2e/${{ parameters.testFolder }}"
          docker run --rm \
            -v $PWD:/e2e \
            -w /e2e \
            cypress/included:13.6.4 \
            run --spec "cypress/e2e/${{ parameters.testFolder }}/**/*.cy.js"
        fi
      displayName: 'Run Cypress Tests with Folder Parameter'
